### ISSUE TITLE
Intervals fails

### ISSUE THREAD

**Issue by krissen** [Tigge/FIT-to-TCX#5]
Works well with "normal" workouts, but when trying to convert interval-workouts, recorded with the Forerunner 610, I get the following:

>Traceback (most recent call last):
>  File "/usr/local/bin/fittotcx.py", line 246, in <module>
>    sys.exit(main())
>  File "/usr/local/bin/fittotcx.py", line 237, in main
>    document = convert(sys.argv[1])
>  File "/usr/local/bin/fittotcx.py", line 219, in convert
>    add_activity(element, activity)
>  File "/usr/local/bin/fittotcx.py", line 208, in add_activity
>    add_lap(actelem, activity, lap)
>  File "/usr/local/bin/fittotcx.py", line 163, in add_lap
>    triggermet = LAP_TRIGGER_MAP[lap.get_data("lap_trigger")]
>KeyError: 9

Sample workout available here: https://www.dropbox.com/s/hf9qj3zx1n6drlv/2015-08-06_21-51-28_4_348.fit?dl=0

Any ideas?

Kind regards,
Kristian

**Comment by Tigge** [comment]
It seems like the Forefunner 610 have generated an invalid value for the FIT type `lap_trigger`. Values 0 to 8 are in the specification (manual, time, distance, position_start, position_lap, position_waypoint, position_marked, session_end, fitness_equipment).

You can replace the line (163) with this. At least it will generate a complete tcx file: 

```python
triggermet = LAP_TRIGGER_MAP.get(lap.get_data("lap_trigger"), "Manual")
```

**Comment by krissen** [comment]
Thanks for the reply & fix, @Tigge!

**Comment by Tigge** [comment]
I was a bit curious how Garmin would handle this case so I upload this to Garmin Connect and downloaded it again and what their generated TCX files would look like. It can handle and import this type of files and it will generate a trigger with value `Manual`.

I'll add a default value like this to all map lookups in a future commit.

**Comment by krissen** [comment]
Yes, that's how I've been handling these interval-files previously. (Exporting them through GC.)

Thanks again for the swift fix.
