### ISSUE TITLE
ImportError: cannot import name Activity

### ISSUE THREAD

**Issue by r-shawgo** [Tigge/FIT-to-TCX#8]
I am late to the party, but I am hoping there is still some support around.  I'm on Ubuntu 17.04 running python 2.7.13 and am receiving the following error when I try to run fittotcx:
  File "/usr/local/bin/fittotcx", line 11, in <module>
    load_entry_point('fit-to-tcx==0.1', 'console_scripts', 'fittotcx')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/fittotcx/program.py", line 34, in <module>
ImportError: cannot import name Activity

**Comment by Tigge** [comment]
Hi. I think `python-fitparse` was recently updated to a 2.0 version. FIT-to-TCX relies on the 1.0 version. Try installing it from the `v1-archive` branch at https://github.com/dtcooper/python-fitparse/releases/tag/v1-archive instead and see if that will work.

**Comment by r-shawgo** [comment]
Thanks, that solved the problem!  
Sadly, it did not solve my initial problem.  I think Wahoo has recently changed something about they way they export .fit files because nothing processes them any longer.  The output fails with "Unexpected exception while parsing (KeyError: 1)" and I think that has nothing to do with your code.  Greatly appreciate the help!

**Comment by Tigge** [comment]
Nice to hear that it solved at least the initial problem. You could try to see if the 2.0 version of fitparse works better for you. There is an FIT to CVS converter there that you could try, and if that works it should be easy enough to update FIT-to-TCX to use the newer version (I should do that anyway). If not it might be a problem with Wahoo. I could take a look at one of the FIT files as well if you'd like (when I got time) to see if I can spot something weird in them.

**Comment by r-shawgo** [comment]
​Thanks.  I think it was a change to the way the fit file is being written
as it seems to have happened after a firmware update the Bolt Element.
I've attached a sample of the fit file.​

**Comment by r-shawgo** [comment]
looks like I did not attach the file.  Trying again.
[Sample Files from Wahoo.zip](https://github.com/Tigge/FIT-to-TCX/files/1228784/Sample.Files.from.Wahoo.zip)

**Comment by Tigge** [comment]
It seems to parse almost fine with the new fitparse version. I've created an issue in the that project -
 see https://github.com/dtcooper/python-fitparse/issues/35 for more information. Once that is fixed I can release a new version of FIT-to-TCX which should work with the Wahoo files.

**Comment by Tigge** [comment]
@r-shawgo this should be solved now and FIT-to-TCX should work on the Wahoo files from now on. Thanks.
